language: generic
sudo: required
dist: trusty

#slack integration
notifications:
  email: false
  slack:
    rooms:
      - palouserobosub:C883XOLXAI646jXLW8zENsVE#software
    on_success: never  
    on_failure: never

#whitelist for branches to build
branches:
  only:
    - master
    - dev
    - travisci

#install dependencies
addons:
  apt:
    sources:
    - sourceline: 'deb http://mirror.umd.edu/packages.ros.org/ros/ubuntu trusty     main'
      key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.key '
    - sourceline: 'deb http://robosub.eecs.wsu.edu/repo/ /'
      key_url: 'http://robosub.eecs.wsu.edu/repo/repository_key'
    packages:
    - robosub

#all dependencies are installed from packages, nothing to do for install
install: true

#build the project
before_script:
  - source /opt/ros/indigo/setup.bash
  - cd ../ && mkdir src && mv robosub src/ && cd src
  - catkin_init_workspace
  - cd ..

script:
  - catkin_make run_tests
