language: generic
sudo: required
dist: xenial

#Slack integration
notifications:
    email: false
    slack:
        rooms:
            - secure: "RjbqgUT8spj/yAu3BotRm+xzNiVAgO63zTyAYNLH2HusmdGZfsGwNNf0XxEUF2okUbRw8mWgSsrBKV2Deh9RE3HvTStjIgk9tJKDNCn/NKDQtK9Vtx/moOONefED1ib82bb0wpsLkc7W5jW159P0r9FhCSkRnsS2Up6+L0gmW0tlyOnfabvla2EV3Xctnw6afZs+GR905h+SsNRWfR4AAtOqyy/YClOFlnnCZ+MmZ/8Dzplp1HgYnjbBZ772h7TfS8N+LRstIMJ8fxWen6q8XlKlRqOHvrLhPwfNN+6527vzhkCY+W3FVGNQuk/6kS+W+HnhLFgxARaZwB3UNMLVYYYgVtJk/PybS3pLts30re9JNovf3bH8M1DL0JCGplStN5ZNnwNjGrqm/j+4hv64Y9H022wizQ8eE4CdGi7Jc8bNAIktbfiFLtJ05hVMrQ6u0H0NXtxODZZUcJmJFS1zsDs4ef4M4vdZ3bT5+CuQEcRggelwvB4sens+h8wCE8z5Z0OQ6ClvsW7FYUJtH+4uU+tnqlwtpgje1EYkrCjk3ZtFRMW5uSwW1f/ryGGUZkp56sxdnOTg95FsXmecECgb0nfCY0/4j/ULcP/zphUmsOjVk54ASvemI80mbQBrJCxTc/dXCxIDzDdANBwcdKglWFaYp0mLC9h4Daz391Wb5Ds="
        on_success: always
        on_failure: always

#Whitelist branches to build
branches:
    only:
        - master
        - travis-ci-docker

#Docker stuff
services:
    - docker

before_install:
    - sudo mkdir -p /etc/docker/certs.d/robosub.eecs.wsu.edu\:443/
    - sudo wget robosub.eecs.wsu.edu/docker/ca.crt -O /etc/docker/certs.d/robosub.eecs.wsu.edu\:443/ca.crt
    - echo "Pulling image..."
    - sudo docker pull robosub.eecs.wsu.edu:443/robosub
    - sudo docker tag robosub.eecs.wsu.edu:443/robosub robosub

install:
    - if [ "$TEST" == "true" ]; then echo "TEST=true" >> env.list; fi
    - if [ "$BUILD" == "true" ]; then echo "BUILD=true" >> env.list; fi
    - if [ "$LINT" == "true" ]; then echo "LINT=true" >> env.list; fi
    - echo "ROBOSUB_HASH=${TRAVIS_COMMIT}" >> env.list;
    - cat env.list;

script:
    - echo "Staring build...";
    - travis_wait docker run --env-file env.list robosub

matrix:
    fast_finish: true
    include:
        - env:
            - BUILD=true
        - env:
            - LINT=true
        - env:
            - TEST=true
