language: generic
sudo: required
dist: trusty

#slack integration
notifications:
  email: false
  slack:
    rooms:
      - palouserobosub:C883XOLXAI646jXLW8zENsVE#software
    on_success: never
    on_failure: never

#whitelist for branches to build
branches:
  only:
    - master
    - dev
    - travisci

#install dependencies
addons:
  apt:
    sources:
    - sourceline: 'deb http://mirror.umd.edu/packages.ros.org/ros/ubuntu trusty     main'
      key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.key '
    - sourceline: 'deb http://robosub.eecs.wsu.edu/repo/ /'
      key_url: 'http://robosub.eecs.wsu.edu/repo/repository_key'
    - sourceline: 'deb http://packages.osrfoundation.org/gazebo/ubuntu trusty main'
      key_url: 'http://packages.osrfoundation.org/gazebo.key'
    packages:
    - robosub

#most dependencies are installed from packages, install just does simulator if needed 
install: 
  - if [ "$TEST" == "true" ] ; then sudo apt-get install robosub-simulator; fi

#build the project
before_script:
  - source /opt/ros/indigo/setup.bash
  - cd ../ && mkdir src && mv robosub src/ && cd src
  - catkin_init_workspace
  - cd ..
  - if [ "$TEST" == "true" ] ; then cd src/; git clone https://github.com/PalouseRobosub/robosub_simulator.git; cd ../; fi

script:
  - if [ "$BUILD" == "true" ] ; then catkin_make; fi
  - if [ "$TEST" == "true" ] ; then catkin_make; source devel/setup.bash; catkin_make run_tests; catkin_test_results; fi
  - if [ "$LINT" == "true" ] ; then catkin_make roslint; fi

matrix:
  fast_finish: true
  allow_failures:
    - env:
      - TEST=true
  include:
    - env: #does just the build work?
      - BUILD=true
    - env: #does the linter pass?
      - LINT=true
    - env: #do all tests pass?
      - TEST=true

