#include <ros/ros.h>

#include <dynamic_reconfigure/server.h>

//This header is generated by dynamic_reconfigure from the file "Dynamic.cfg"
//Headers are automatically generated with Config at the end, so beware of
//    naming .cfg files with the word Config.
#include <robosub/DynamicConfig.h>


void callback(const robosub::DynamicConfig &config, uint32_t level)
{
    ROS_INFO("Reconfigure Request: %d %f %s %s %d",
          config.int_param, config.double_param,
          config.str_param.c_str(),
          config.bool_param?"True":"False",
          config.size);
}

int main (int argc, char **argv)
{
    ros::init(argc, argv, "dynamic_parameters");

    dynamic_reconfigure::Server<robosub::DynamicConfig> server;
    dynamic_reconfigure::Server<robosub::DynamicConfig>::CallbackType f;

    f = boost::bind(&callback, _1, _2);
    server.setCallback(f);

    ROS_INFO("Spinning node");
    ros::spin();
    return 0;
}
