#!/bin/bash
# This script is used for delaying the launching of nodes within a launch file.
# The first (and only) parameter is the delay time (in seconds).
# The remaining parameters are generated by roslaunch.
#
# Launch file usage example:
# <node name="bno055_left" pkg="robosub" type="bno055_sensor" launch-prefix="$(find robosub)/scripts/sleepme.sh 3"/>

sleep $1
$2 ${@:3}
