#!/bin/bash

# Parse the PACKAGE_PATH into an array
arrROS_PACKAGE_PATH=(${ROS_PACKAGE_PATH//:/ })

# Find the location that contains the robosub sub directory
for i in "${arrROS_PACKAGE_PATH[@]}"
do
    if [ -d "$i/robosub" ]; then
        cd $i/..
    fi
done

if [ "$1" -eq "ninja" ]
then
    echo "Using Ninja"
    catkin_make --use-ninja
else
    echo "Using Make"
    catkin_make
fi
