sensor:
    axis:
        x: 1
        y: 2
        z: 3
    accelerometer:
        offset:
            x: -10
            y: 79
            z: 45
        radius: 1000
    magnetometer:
        offset:
            x: 1665
            y: -770
            z: 3696
        radius: 308
    gyroscope:
        offset:
            x: -1
            y: 1
            z: 0

