sensor:
    axis:
        x: 1
        y: 2
        z: 3
    accelerometer:
        offset:
            x: -7
            y: 37
            z: 1
        radius: 1000
    magnetometer:
        offset:
            x: -221
            y: -49
            z: -60
        radius: 751
    gyroscope:
        offset:
            x: -1
            y: -1
            z: 0

