ports:
    thruster: "/dev/maestro_control"
    sensor: "/dev/bno055"
thrusters:
    -   name: "dive_front_left"
        channel: 8
        max_speed: 0.6
        orientation:
            x: 0.0
            y: 0.0
            z: -1.0
        position:
            x: 0.235
            y: 0.23
            z: -0.1
    -   name: "dive_front_right"
        channel: 7
        max_speed: 0.6
        orientation:
            x: 0.0
            y: 0.0
            z: -1.0
        position:
            x: 0.235
            y: -0.23
            z: -0.1
    -   name: "dive_back_left"
        channel: 4
        max_speed: 0.6
        orientation:
            x: 0.0
            y: 0.0
            z: -1.0
        position:
            x: -0.235
            y: 0.23
            z: -0.1
    -   name: "dive_back_right"
        channel: 6
        max_speed: 0.6
        orientation:
            x: 0.0
            y: 0.0
            z: -1.0
        position:
            x: -0.235
            y: -0.23
            z: -0.1
    -   name: "strafe_front"
        channel: 9
        max_speed: 0.6
        orientation:
            x: 0.0
            y: 1.0
            z: 0.0
        position:
            x: 0.46
            y: 0.0
            z: -0.01
    -   name: "strafe_back"
        channel: 0
        max_speed: 0.6
        orientation:
            x: 0.0
            y: 1.0
            z: 0.0
        position:
            x: -0.46
            y: 0.0
            z: -0.01
    -   name: "forward_left"
        channel: 10
        max_speed: 0.6
        orientation:
            x: -1.0
            y: 0.0
            z: 0.0
        position:
            x: 0.0
            y: 0.2075
            z: -0.01
    -   name: "forward_right"
        channel: 1
        max_speed: 0.6
        orientation:
            x: -1.0
            y: 0.0
            z: 0.0
        position:
            x: 0.0
            y: -0.2075
            z: -0.01
control:
    rate: 10
    mass: 27.0
    back_thrust_ratio: 0.8
    max_thrust: 50.0
    inertia:
        psi: 1.0
        phi: 1.0
        theta: 1.0
    proportional:
        x: 1.0
        y: 1.0
        z: 4.0
        psi: 0.04 #roll
        phi: 0.04 #pitch
        theta: 0.07 #yaw
    integral:
        x: 0.0
        y: 0.0
        z: 0.0
        psi: 0.0
        phi: 0.0
        theta: 0.0
    derivative:
        x: 0.0
        y: 0.0
        z: 0.0
        psi: 0.0
        phi: 0.0
        theta: 0.0
    windup:
        x: 5.0
        y: 5.0
        z: 5.0
        psi: 45.0
        phi: 45.0
        theta: 45.0
    hysteresis:
        x: 0.0
        y: 0.0
        z: 0.0
        psi: 0.0
        phi: 0.0
        theta: 0.0
    limits:
        rotation: 0.5
        translation: 0.5
    buoyancy_offset: 0.0
depth:
    rate: 10
sensor:
    rate: 20
    axis:
        x: 1
        y: 2
        z: 3
    accelerometer:
        offset:
            x: 0
            y: 0
            z: 0
        radius: 0
    magnetometer:
        offset:
            x: 0
            y: 0
            z: 0
        radius: 0
    gyroscope:
        offset:
            x: 0
            y: 0
            z: 0
hydrophones:
    pinger:
        depth: -4.9
    reference:
        x: 0
        y: 0
        z: 0
    positions:
        delta: 3
        epsilon: 3
        zeta: 3
